services:
  pihole:
    image: pihole/pihole:2025.02.6
    container_name: pihole
    hostname: pihole
    environment:
      TZ: 'Europe/Paris'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      - pihole_network
    restart: unless-stopped

  unbound:
    container_name: unbound
    build: ./unbound
    networks:
      - pihole_network
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile'
      - './caddy_data:/data'
      - './caddy_config:/config'
    networks:
      - pihole_network
    restart: unless-stopped

  dnsproxy:
    image: adguard/dnsproxy:latest
    container_name: dnsproxy
    ports:
      - '853:853'
    restart: unless-stopped
    volumes:
      - './caddy_data:/data'
    command:
      - -u
      - pihole:53
      - -c
      - /data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/your-domain-name/your-domain-name.crt
      - -k
      - /data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/your-domain-name/your-domain-name.key
      - -t
      - "853"
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge

