services:
  pihole:
    image: pihole/pihole:2025.04.0
    container_name: pihole
    hostname: pihole
    environment:
      TZ: 'Europe/Paris'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      - pihole_network
    restart: unless-stopped

  unbound:
    container_name: unbound
    build: ./unbound
    networks:
      - pihole_network
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile'
      - './caddy_data:/data'
      - './caddy_config:/config'
    env_file:
      - .env
    networks:
      - pihole_network
    restart: unless-stopped

  dnsproxy:
    image: adguard/dnsproxy:latest
    container_name: dnsproxy
    ports:
      - '853:853'
    restart: unless-stopped
    volumes:
      - './caddy_data:/data'
    env_file:
      - .env
    command:
      - -u
      - pihole:53
      - -c
      - /data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${FQDN}/${FQDN}.crt
      - -k
      - /data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${FQDN}/${FQDN}.key
      - -t
      - "853"
    networks:
      - pihole_network

networks:
  pihole_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

